
- name: mkdir 

  hosts: localhost
  tasks:
    - name: ensure backup folder is created
      file:
        path: "{{ backup_root }}"
        state: directory
      run_once: yes


- name: Backup config      
  hosts: routers
