- name: backup configuration
  hosts: all
  gather_facts: false
  connection: network_cli

  vars:
    backup_root: ~/backups

    cli:
      host: "{{ inventory_hostname }}"
#      username: cisco
#      password: cisco@123
#      authorize: true

  tasks:
    - name: run show running-config on remote devices
      ios_command:
        commands: "show running-config"
        provider: "{{ cli }}"
      register: config

    - name: ensure backup folder is created
      file:
        path: "{{ backup_root }}/{{ site_name }}"
        state: directory
      run_once: yes
      delegate_to: localhost

    - name: ensure device rolder is created
      file:
        path: "{{ backup_root }}//{{ site_name }}/{{ inventory_hostname }}"
        state: directory
      delegate_to: localhost

    - name: get timestamp
      command: date +%Y%m%d
      register: timestamp
      delegate_to: localhost
    - name: get/copy backup
      copy:
        content: "{{ config.stdout[0] }}"
        dest: "{{ backup_root }}/{{ site_name }}/{{ inventory_hostname }}/running-config_{{ timestamp.stdout }}"
      delegate_to: localhost