- name: Cisco lab site-01
  hosts: CORE-sw
  gather_facts: false

  tasks:
    - name: configure interface settings
      ios_config:
        lines:
          - description config interface trunk
          - sw trunk encap dot1q
          - sw mode trunk
        parents: interface Ethernet0/1-3
      register: output

    - name: print output
      debug:
        var: output.stdout_lines




  # example
  # tasks:
    # - name: config core-switch
      # ios_command:
        # commands: show version | incl Version
      # register: output
    # - name: configure interface settings
      # ios_config:
        # lines:
          # - description test interface
          # - no ip address 172.31.1.1 255.255.255.0
        # parents: interface Ethernet1/0
      # register: output
# 
    # - name: print output
    # debug:
        # var: output.stdout_lines
