- name: Cisco show version example
  hosts: vyos
  gather_facts: false

  tasks:
    - name: run show version on the routers
      ios_command:
        commands: 
        - ping 8.8.8.8
      register: output

    - name: print output
      debug:
        var: output.stdout_lines
