- name: backup configuration
  hosts: all
  gather_facts: false
  connection: network_cli

  vars:
    root_path: /var/lib/ol-automation-manager/github
    backup_root: "{{ root_path }}/backups_config"
    timestamp: ""
    cli:
      host: "{{ inventory_hostname }}"
#      username: 
#      password: 
#      authorize: true

  tasks:
    - name: run show running-config on remote devices
      ios_command:
        commands: "show running-config"
#        provider: "{{ cli }}"
      register: config

    - name: ensure backup folder is created
      file:
        path: "{{ backup_root }}/{{ site_name }}"
        state: directory
      run_once: yes
      delegate_to: localhost

    - name: ensure device rolder is created
      file:
        path: "{{ backup_root }}//{{ site_name }}/{{ inventory_hostname }}"
        state: directory
      delegate_to: localhost

    - name: get timestamp for play
      set_fact:
        timestamp: "{{ lookup('pipe','date +%Y-%m-%d-%H-%M') }}"
      delegate_to: localhost

# copy file backup to ./backups_config
    - name: backup to /backups_config
      copy:
        content: "{{ config.stdout[0] }}"
        dest: "{{ backup_root }}/{{ site_name }}/{{ inventory_hostname }}/{{ timestamp }}"   #{{ timestamp.stdout }}
      delegate_to: localhost

# copy file backup to ./config_change_info/backups_config
    - name: backup to /config_change_info/backups_config
      copy:
        content: "{{ config.stdout[0] }}"
        dest: "{{ backup_root }}/{{ site_name }}/{{ inventory_hostname }}/backup-config_{{ inventory_hostname }}"   #{{ timestamp.stdout }}
      delegate_to: localhost

    - name: find backups
      find:
        paths: "{{ backup_root }}"
        file_type: directory
      register: backups
      run_once: true
      become: true
      delegate_to: localhost
      delegate_facts: true

    - name: create restore job template
      awx.awx.job_template:
        name: "Network Automation - Restore"
        job_type: "run"
        inventory: "{{ restore_inventory|default('test') }}"
        project: "{{ restore_project|default('git_pb_public') }}"
        playbook: "{{ restores_playbook|default('zpb/restore.yml') }}"
        credential: "{{ restore_credential|default('cisco_pw') }}"
        survey_enabled: true
        survey_spec: "{{ lookup('template', '{{ playbook_dir }}/network_setup/templates/backup.j2') }}"
        validate_certs: no
        organization: "Default"
      run_once: true

