---
- name: retrieve network configurations
  hosts: site03
  gather_facts: false

  tasks:
    # fail with good error for Automation controller user

    - name: backup configuration
      include_role:
        name: "../roles/backup"
      when: ansible_network_os is defined

    - name: create time stamp for play
      set_fact:
        datetime: "{{ lookup('pipe','date +%Y-%m-%d-%H-%M') }}"
      delegate_to: localhost
      delegate_facts: true
      run_once: true

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /backup/
        state: directory
      delegate_to: localhost
      become: true
      run_once: true

    - name: save configuration to backup server
      copy:
        src: "{{ config_output.backup_path }}"
        dest: "/backup/{{hostvars['backup-server'].datetime}}/"
      when: config_output is defined
      become: true
      delegate_to: localhost

    - name: find backups
      find:
        paths: /backup
        file_type: directory
      register: backups
      run_once: true
      become: true
      delegate_to: localhost
      delegate_facts: true

    - name: create restore job template
      awx.awx.job_template:
        name: "Network Automation - Restore"
        job_type: "run"
        inventory: "{{ restore_inventory|default('test') }}"
        project: "{{ restore_project|default('git_pb_public') }}"
        playbook: "{{ restores_playbook|default('playbooks/network_restore.yml') }}"
        credential: "{{ restore_credential|default('cisco_pw') }}"
        survey_enabled: true
        survey_spec: "{{ lookup('template', '{{ playbook_dir }}/../network_setup/templates/backup.j2') }}"
        validate_certs: no
        organization: "Default"
      run_once: true
